/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.YdlidarRosDriver
{
    public class LaserFan : Message
    {
        public const string RosMessageName = "ydlidar_ros_driver/LaserFan";

        public Header header { get; set; }
        public float angle_min { get; set; }
        public float angle_max { get; set; }
        public float time_increment { get; set; }
        public float scan_time { get; set; }
        public float range_min { get; set; }
        public float range_max { get; set; }
        public float[] angles { get; set; }
        public float[] ranges { get; set; }
        public float[] intensities { get; set; }

        public LaserFan()
        {
            this.header = new Header();
            this.angle_min = 0.0f;
            this.angle_max = 0.0f;
            this.time_increment = 0.0f;
            this.scan_time = 0.0f;
            this.range_min = 0.0f;
            this.range_max = 0.0f;
            this.angles = new float[0];
            this.ranges = new float[0];
            this.intensities = new float[0];
        }

        public LaserFan(Header header, float angle_min, float angle_max, float time_increment, float scan_time, float range_min, float range_max, float[] angles, float[] ranges, float[] intensities)
        {
            this.header = header;
            this.angle_min = angle_min;
            this.angle_max = angle_max;
            this.time_increment = time_increment;
            this.scan_time = scan_time;
            this.range_min = range_min;
            this.range_max = range_max;
            this.angles = angles;
            this.ranges = ranges;
            this.intensities = intensities;
        }
    }
}
